name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    
    # dotnet build and publish
    - name: Build with dotnet
      run: |
       cd src/ProtoInput
       echo "$(pwd)"
       ls
       dotnet build --configuration Release
    - name: dotnet publish
      run: |
        cd src/ProtoInput
        echo "$(pwd)"
        ls
        dotnet publish -c Release -o dotnetcorewebapp 